# docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: ./venv1/bin/python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    env_file:
      - .env

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:

