---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: default
  labels:
    app: mysql-db
spec:
  clusterIP: None        
  selector:
    app: mysql-db        
  ports:
    - name: mysql
      port: 3306         
      targetPort: 3306   

