apiVersion: v1
kind: Secret
metadata:
  name: aws-registry-key
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "${AWS_ECR_SERVER}": {
          "username": "${DOCKER_USERNAME}",
          "password": "${DOCKER_PASSWORD}"
        }
      }
    }
